# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from uarpb.v1 import runtime_pb2 as uarpb_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uarpb/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/uar.v1.Runtime/Infer',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.unary_stream(
                '/uar.v1.Runtime/InferStream',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/uar.v1.Runtime/ExecuteTool',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ToolRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ToolResult.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/uar.v1.Runtime/ListTools',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/uar.v1.Runtime/ListModels',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/uar.v1.Runtime/RegisterAgent',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AgentVersion.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/uar.v1.Runtime/StartRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/uar.v1.Runtime/GetRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.WatchRun = channel.unary_stream(
                '/uar.v1.Runtime/WatchRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/uar.v1.Runtime/CancelRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.ResolveRun = channel.unary_unary(
                '/uar.v1.Runtime/ResolveRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.DryRun = channel.unary_unary(
                '/uar.v1.Runtime/DryRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.DryRunReport.FromString,
                _registered_method=True)
        self.DecideApproval = channel.unary_unary(
                '/uar.v1.Runtime/DecideApproval',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
                _registered_method=True)
        self.ListApprovals = channel.unary_unary(
                '/uar.v1.Runtime/ListApprovals',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListApprovalsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListApprovalsResponse.FromString,
                _registered_method=True)
        self.GetApproval = channel.unary_unary(
                '/uar.v1.Runtime/GetApproval',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetApprovalRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
                _registered_method=True)
        self.VerifyAudit = channel.unary_unary(
                '/uar.v1.Runtime/VerifyAudit',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.VerifyAuditRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AuditVerification.FromString,
                _registered_method=True)
        self.ExportAudit = channel.unary_unary(
                '/uar.v1.Runtime/ExportAudit',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ExportAuditRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ExportAuditResponse.FromString,
                _registered_method=True)
        self.GetRuntimeInfo = channel.unary_unary(
                '/uar.v1.Runtime/GetRuntimeInfo',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetRuntimeInfoRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.RuntimeInfo.FromString,
                _registered_method=True)
        self.ListUsage = channel.unary_unary(
                '/uar.v1.Runtime/ListUsage',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListUsageRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListUsageResponse.FromString,
                _registered_method=True)
        self.ListApiKeys = channel.unary_unary(
                '/uar.v1.Runtime/ListApiKeys',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListApiKeysRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListApiKeysResponse.FromString,
                _registered_method=True)
        self.CreateApiKey = channel.unary_unary(
                '/uar.v1.Runtime/CreateApiKey',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.CreatedApiKey.FromString,
                _registered_method=True)
        self.RevokeApiKey = channel.unary_unary(
                '/uar.v1.Runtime/RevokeApiKey',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RevokeApiKeyRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ApiKeyInfo.FromString,
                _registered_method=True)
        self.GetAccessPolicy = channel.unary_unary(
                '/uar.v1.Runtime/GetAccessPolicy',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetAccessPolicyRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AccessPolicy.FromString,
                _registered_method=True)
        self.ListLogs = channel.unary_unary(
                '/uar.v1.Runtime/ListLogs',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListLogsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListLogsResponse.FromString,
                _registered_method=True)
        self.GetStsInfo = channel.unary_unary(
                '/uar.v1.Runtime/GetStsInfo',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetStsInfoRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.StsInfo.FromString,
                _registered_method=True)
        self.ListApps = channel.unary_unary(
                '/uar.v1.Runtime/ListApps',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListAppsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListAppsResponse.FromString,
                _registered_method=True)
        self.RegisterApp = channel.unary_unary(
                '/uar.v1.Runtime/RegisterApp',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAppRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AppCredentials.FromString,
                _registered_method=True)
        self.CreateAppSecret = channel.unary_unary(
                '/uar.v1.Runtime/CreateAppSecret',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.CreateAppSecretRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AppCredentials.FromString,
                _registered_method=True)
        self.RevokeAppSecret = channel.unary_unary(
                '/uar.v1.Runtime/RevokeAppSecret',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RevokeAppSecretRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AppRegistration.FromString,
                _registered_method=True)
        self.DisableApp = channel.unary_unary(
                '/uar.v1.Runtime/DisableApp',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.DisableAppRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AppRegistration.FromString,
                _registered_method=True)
        self.RotateSigningKey = channel.unary_unary(
                '/uar.v1.Runtime/RotateSigningKey',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RotateSigningKeyRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.StsInfo.FromString,
                _registered_method=True)
        self.CheckContent = channel.unary_unary(
                '/uar.v1.Runtime/CheckContent',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.CheckContentRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.CheckContentResult.FromString,
                _registered_method=True)
        self.RegisterPlugin = channel.unary_unary(
                '/uar.v1.Runtime/RegisterPlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/uar.v1.Runtime/ListPlugins',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.ActivatePlugin = channel.unary_unary(
                '/uar.v1.Runtime/ActivatePlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)
        self.RollbackPlugin = channel.unary_unary(
                '/uar.v1.Runtime/RollbackPlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)


class RuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Synchronous inference. With `agent` set, starts that agent and waits for its result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request, context):
        """Streaming inference: start, token deltas, usage, exactly one terminal event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRun(self, request, context):
        """Ordered, durable run events. Resumable: pass the last seen seq as after_seq.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRun(self, request, context):
        """Resolve a run in needs_attention after an ambiguous external write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DryRun(self, request, context):
        """Offline: never calls a model, tool, plugin or network endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideApproval(self, request, context):
        """Approvals. A decision is bound to the action and the hash of its arguments; it is accepted once,
        only while pending and unexpired, only from a principal of the same tenant with approvals:decide
        (and one of the approver roles, when the approval names them), never from the requester.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApprovals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAudit(self, request, context):
        """Tamper-evident audit (permission audit:read). Each tenant's audit rows form a hash chain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeInfo(self, request, context):
        """Administration. Tenant-scoped like every other call, except logs and runtime components, which
        describe the process (restricted to the configured platform tenants).
        admin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsage(self, request, context):
        """usage:read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApiKeys(self, request, context):
        """keys:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """keys:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApiKey(self, request, context):
        """keys:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessPolicy(self, request, context):
        """keys:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLogs(self, request, context):
        """logs:read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStsInfo(self, request, context):
        """Application registration for the built-in token service (STS). Applications exchange their
        client credentials for access tokens at POST /api/v1/oauth/token (OAuth 2.0 client_credentials,
        RFC 6749 section 4.4; HTTP only) and call every other operation with "Authorization: Bearer".
        apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApps(self, request, context):
        """apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterApp(self, request, context):
        """apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAppSecret(self, request, context):
        """apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAppSecret(self, request, context):
        """apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableApp(self, request, context):
        """apps:manage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateSigningKey(self, request, context):
        """platform administrators
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckContent(self, request, context):
        """Guardrails: run the caller's tenant policy over a text without calling a model
        (pre-validate content, test a policy). Permission guardrails:check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlugin(self, request, context):
        """Plugins (administrators only). Versions are immutable; activation validates and health-checks
        the version and affects new runs only (running runs keep the versions they started with).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivatePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.SerializeToString,
            ),
            'InferStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Event.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ToolRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ToolResult.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AgentVersion.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'WatchRun': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Event.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'ResolveRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'DryRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DryRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.DryRunReport.SerializeToString,
            ),
            'DecideApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideApproval,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Approval.SerializeToString,
            ),
            'ListApprovals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApprovals,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListApprovalsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListApprovalsResponse.SerializeToString,
            ),
            'GetApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApproval,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetApprovalRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Approval.SerializeToString,
            ),
            'VerifyAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAudit,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.VerifyAuditRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AuditVerification.SerializeToString,
            ),
            'ExportAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportAudit,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ExportAuditRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ExportAuditResponse.SerializeToString,
            ),
            'GetRuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeInfo,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetRuntimeInfoRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.RuntimeInfo.SerializeToString,
            ),
            'ListUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsage,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListUsageRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListUsageResponse.SerializeToString,
            ),
            'ListApiKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApiKeys,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListApiKeysRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListApiKeysResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.CreatedApiKey.SerializeToString,
            ),
            'RevokeApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApiKey,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RevokeApiKeyRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ApiKeyInfo.SerializeToString,
            ),
            'GetAccessPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessPolicy,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetAccessPolicyRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AccessPolicy.SerializeToString,
            ),
            'ListLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLogs,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListLogsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListLogsResponse.SerializeToString,
            ),
            'GetStsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStsInfo,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetStsInfoRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.StsInfo.SerializeToString,
            ),
            'ListApps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApps,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListAppsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListAppsResponse.SerializeToString,
            ),
            'RegisterApp': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterApp,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAppRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AppCredentials.SerializeToString,
            ),
            'CreateAppSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAppSecret,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.CreateAppSecretRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AppCredentials.SerializeToString,
            ),
            'RevokeAppSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAppSecret,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RevokeAppSecretRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AppRegistration.SerializeToString,
            ),
            'DisableApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableApp,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.DisableAppRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AppRegistration.SerializeToString,
            ),
            'RotateSigningKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateSigningKey,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RotateSigningKeyRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.StsInfo.SerializeToString,
            ),
            'CheckContent': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckContent,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.CheckContentRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.CheckContentResult.SerializeToString,
            ),
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.SerializeToString,
            ),
            'ActivatePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivatePlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
            'RollbackPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackPlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uar.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uar.v1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/Infer',
            uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uar.v1.Runtime/InferStream',
            uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ExecuteTool',
            uarpb_dot_v1_dot_runtime__pb2.ToolRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ToolResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListTools',
            uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListModels',
            uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RegisterAgent',
            uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AgentVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/StartRun',
            uarpb_dot_v1_dot_runtime__pb2.RunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetRun',
            uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uar.v1.Runtime/WatchRun',
            uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/CancelRun',
            uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ResolveRun',
            uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DryRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/DryRun',
            uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.DryRunReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/DecideApproval',
            uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListApprovals',
            uarpb_dot_v1_dot_runtime__pb2.ListApprovalsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListApprovalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetApproval',
            uarpb_dot_v1_dot_runtime__pb2.GetApprovalRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/VerifyAudit',
            uarpb_dot_v1_dot_runtime__pb2.VerifyAuditRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AuditVerification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ExportAudit',
            uarpb_dot_v1_dot_runtime__pb2.ExportAuditRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ExportAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetRuntimeInfo',
            uarpb_dot_v1_dot_runtime__pb2.GetRuntimeInfoRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.RuntimeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListUsage',
            uarpb_dot_v1_dot_runtime__pb2.ListUsageRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApiKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListApiKeys',
            uarpb_dot_v1_dot_runtime__pb2.ListApiKeysRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListApiKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/CreateApiKey',
            uarpb_dot_v1_dot_runtime__pb2.CreateApiKeyRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.CreatedApiKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RevokeApiKey',
            uarpb_dot_v1_dot_runtime__pb2.RevokeApiKeyRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ApiKeyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetAccessPolicy',
            uarpb_dot_v1_dot_runtime__pb2.GetAccessPolicyRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AccessPolicy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListLogs',
            uarpb_dot_v1_dot_runtime__pb2.ListLogsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetStsInfo',
            uarpb_dot_v1_dot_runtime__pb2.GetStsInfoRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.StsInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListApps',
            uarpb_dot_v1_dot_runtime__pb2.ListAppsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListAppsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RegisterApp',
            uarpb_dot_v1_dot_runtime__pb2.RegisterAppRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AppCredentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAppSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/CreateAppSecret',
            uarpb_dot_v1_dot_runtime__pb2.CreateAppSecretRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AppCredentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAppSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RevokeAppSecret',
            uarpb_dot_v1_dot_runtime__pb2.RevokeAppSecretRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AppRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/DisableApp',
            uarpb_dot_v1_dot_runtime__pb2.DisableAppRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AppRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateSigningKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RotateSigningKey',
            uarpb_dot_v1_dot_runtime__pb2.RotateSigningKeyRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.StsInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/CheckContent',
            uarpb_dot_v1_dot_runtime__pb2.CheckContentRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.CheckContentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RegisterPlugin',
            uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListPlugins',
            uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivatePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ActivatePlugin',
            uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RollbackPlugin',
            uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
