# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from uarpb.v1 import runtime_pb2 as uarpb_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uarpb/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/uar.v1.Runtime/Infer',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.InferStream = channel.unary_stream(
                '/uar.v1.Runtime/InferStream',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/uar.v1.Runtime/ExecuteTool',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ToolRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ToolResult.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/uar.v1.Runtime/ListTools',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/uar.v1.Runtime/ListModels',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/uar.v1.Runtime/RegisterAgent',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.AgentVersion.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/uar.v1.Runtime/StartRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/uar.v1.Runtime/GetRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.WatchRun = channel.unary_stream(
                '/uar.v1.Runtime/WatchRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/uar.v1.Runtime/CancelRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.ResolveRun = channel.unary_unary(
                '/uar.v1.Runtime/ResolveRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
                _registered_method=True)
        self.DryRun = channel.unary_unary(
                '/uar.v1.Runtime/DryRun',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.DryRunReport.FromString,
                _registered_method=True)
        self.DecideApproval = channel.unary_unary(
                '/uar.v1.Runtime/DecideApproval',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
                _registered_method=True)
        self.RegisterPlugin = channel.unary_unary(
                '/uar.v1.Runtime/RegisterPlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/uar.v1.Runtime/ListPlugins',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.ActivatePlugin = channel.unary_unary(
                '/uar.v1.Runtime/ActivatePlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)
        self.RollbackPlugin = channel.unary_unary(
                '/uar.v1.Runtime/RollbackPlugin',
                request_serializer=uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.SerializeToString,
                response_deserializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
                _registered_method=True)


class RuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Synchronous inference. With `agent` set, starts that agent and waits for its result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferStream(self, request, context):
        """Streaming inference: start, token deltas, usage, exactly one terminal event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRun(self, request, context):
        """Ordered, durable run events. Resumable: pass the last seen seq as after_seq.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveRun(self, request, context):
        """Resolve a run in needs_attention after an ambiguous external write.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DryRun(self, request, context):
        """Offline: never calls a model, tool, plugin or network endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideApproval(self, request, context):
        """Contract reserved for M9; the MVP returns UNIMPLEMENTED / HTTP 501.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlugin(self, request, context):
        """Plugins (administrators only). Versions are immutable; activation validates and health-checks
        the version and affects new runs only (running runs keep the versions they started with).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivatePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.SerializeToString,
            ),
            'InferStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InferStream,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Event.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ToolRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ToolResult.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.AgentVersion.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'WatchRun': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Event.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'ResolveRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Run.SerializeToString,
            ),
            'DryRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DryRun,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.DryRunReport.SerializeToString,
            ),
            'DecideApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideApproval,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.Approval.SerializeToString,
            ),
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.SerializeToString,
            ),
            'ActivatePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivatePlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
            'RollbackPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackPlugin,
                    request_deserializer=uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.FromString,
                    response_serializer=uarpb_dot_v1_dot_runtime__pb2.PluginVersion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uar.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uar.v1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/Infer',
            uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uar.v1.Runtime/InferStream',
            uarpb_dot_v1_dot_runtime__pb2.InferenceRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ExecuteTool',
            uarpb_dot_v1_dot_runtime__pb2.ToolRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ToolResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListTools',
            uarpb_dot_v1_dot_runtime__pb2.ListToolsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListModels',
            uarpb_dot_v1_dot_runtime__pb2.ListModelsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RegisterAgent',
            uarpb_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.AgentVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/StartRun',
            uarpb_dot_v1_dot_runtime__pb2.RunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/GetRun',
            uarpb_dot_v1_dot_runtime__pb2.GetRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uar.v1.Runtime/WatchRun',
            uarpb_dot_v1_dot_runtime__pb2.WatchRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/CancelRun',
            uarpb_dot_v1_dot_runtime__pb2.CancelRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ResolveRun',
            uarpb_dot_v1_dot_runtime__pb2.ResolveRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DryRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/DryRun',
            uarpb_dot_v1_dot_runtime__pb2.DryRunRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.DryRunReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/DecideApproval',
            uarpb_dot_v1_dot_runtime__pb2.ApprovalDecision.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.Approval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RegisterPlugin',
            uarpb_dot_v1_dot_runtime__pb2.RegisterPluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ListPlugins',
            uarpb_dot_v1_dot_runtime__pb2.ListPluginsRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivatePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/ActivatePlugin',
            uarpb_dot_v1_dot_runtime__pb2.ActivatePluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.v1.Runtime/RollbackPlugin',
            uarpb_dot_v1_dot_runtime__pb2.RollbackPluginRequest.SerializeToString,
            uarpb_dot_v1_dot_runtime__pb2.PluginVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
