# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from uarpb.plugin.v1 import plugin_pb2 as uarpb_dot_plugin_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uarpb/plugin/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/uar.plugin.v1.Plugin/Describe',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginDescriptor.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/uar.plugin.v1.Plugin/Init',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/uar.plugin.v1.Plugin/Execute',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteResponse.FromString,
                _registered_method=True)
        self.ExecuteStream = channel.unary_stream(
                '/uar.plugin.v1.Plugin/ExecuteStream',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/uar.plugin.v1.Plugin/Health',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/uar.plugin.v1.Plugin/Shutdown',
                request_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class PluginServicer:
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.DescribeRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginDescriptor.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteResponse.SerializeToString,
            ),
            'ExecuteStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.FromString,
                    response_serializer=uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uar.plugin.v1.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uar.plugin.v1.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.plugin.v1.Plugin/Describe',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.DescribeRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.plugin.v1.Plugin/Init',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.plugin.v1.Plugin/Execute',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uar.plugin.v1.Plugin/ExecuteStream',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginExecuteRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.PluginEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.plugin.v1.Plugin/Health',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uar.plugin.v1.Plugin/Shutdown',
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
            uarpb_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
