// Universal AI Runtime — public contract, version 1. Wire package: uar.v1.
// (Stored under proto/uarpb/ so generated Python stubs import as `uarpb`, leaving `uar` to the SDK.)
// This file is the source of truth. OpenAPI and JSON Schemas under contracts/generated
// are produced from it by scripts/gen_contracts.py; never edit them by hand.
//
// JSON mapping: proto3 canonical JSON with original (snake_case) field names.
// Streamed Event messages additionally carry "type": <name of the populated `body` field>.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: uarpb/v1/runtime.proto

package uarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_Infer_FullMethodName          = "/uar.v1.Runtime/Infer"
	Runtime_InferStream_FullMethodName    = "/uar.v1.Runtime/InferStream"
	Runtime_ExecuteTool_FullMethodName    = "/uar.v1.Runtime/ExecuteTool"
	Runtime_ListTools_FullMethodName      = "/uar.v1.Runtime/ListTools"
	Runtime_ListModels_FullMethodName     = "/uar.v1.Runtime/ListModels"
	Runtime_RegisterAgent_FullMethodName  = "/uar.v1.Runtime/RegisterAgent"
	Runtime_StartRun_FullMethodName       = "/uar.v1.Runtime/StartRun"
	Runtime_GetRun_FullMethodName         = "/uar.v1.Runtime/GetRun"
	Runtime_WatchRun_FullMethodName       = "/uar.v1.Runtime/WatchRun"
	Runtime_CancelRun_FullMethodName      = "/uar.v1.Runtime/CancelRun"
	Runtime_ResolveRun_FullMethodName     = "/uar.v1.Runtime/ResolveRun"
	Runtime_DryRun_FullMethodName         = "/uar.v1.Runtime/DryRun"
	Runtime_DecideApproval_FullMethodName = "/uar.v1.Runtime/DecideApproval"
	Runtime_RegisterPlugin_FullMethodName = "/uar.v1.Runtime/RegisterPlugin"
	Runtime_ListPlugins_FullMethodName    = "/uar.v1.Runtime/ListPlugins"
	Runtime_ActivatePlugin_FullMethodName = "/uar.v1.Runtime/ActivatePlugin"
	Runtime_RollbackPlugin_FullMethodName = "/uar.v1.Runtime/RollbackPlugin"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	// Synchronous inference. With `agent` set, starts that agent and waits for its result.
	Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	// Streaming inference: start, token deltas, usage, exactly one terminal event.
	InferStream(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentVersion, error)
	StartRun(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*Run, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error)
	// Ordered, durable run events. Resumable: pass the last seen seq as after_seq.
	WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Idempotent.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error)
	// Resolve a run in needs_attention after an ambiguous external write.
	ResolveRun(ctx context.Context, in *ResolveRunRequest, opts ...grpc.CallOption) (*Run, error)
	// Offline: never calls a model, tool, plugin or network endpoint.
	DryRun(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*DryRunReport, error)
	// Contract reserved for M9; the MVP returns UNIMPLEMENTED / HTTP 501.
	DecideApproval(ctx context.Context, in *ApprovalDecision, opts ...grpc.CallOption) (*Approval, error)
	// Plugins (administrators only). Versions are immutable; activation validates and health-checks
	// the version and affects new runs only (running runs keep the versions they started with).
	RegisterPlugin(ctx context.Context, in *RegisterPluginRequest, opts ...grpc.CallOption) (*PluginVersion, error)
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	ActivatePlugin(ctx context.Context, in *ActivatePluginRequest, opts ...grpc.CallOption) (*PluginVersion, error)
	RollbackPlugin(ctx context.Context, in *RollbackPluginRequest, opts ...grpc.CallOption) (*PluginVersion, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, Runtime_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) InferStream(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_InferStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_InferStreamClient = grpc.ServerStreamingClient[Event]

func (c *runtimeClient) ExecuteTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, Runtime_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*AgentVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentVersion)
	err := c.cc.Invoke(ctx, Runtime_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StartRun(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, Runtime_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, Runtime_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[1], Runtime_WatchRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRunRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchRunClient = grpc.ServerStreamingClient[Event]

func (c *runtimeClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, Runtime_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ResolveRun(ctx context.Context, in *ResolveRunRequest, opts ...grpc.CallOption) (*Run, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Run)
	err := c.cc.Invoke(ctx, Runtime_ResolveRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DryRun(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*DryRunReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunReport)
	err := c.cc.Invoke(ctx, Runtime_DryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DecideApproval(ctx context.Context, in *ApprovalDecision, opts ...grpc.CallOption) (*Approval, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Approval)
	err := c.cc.Invoke(ctx, Runtime_DecideApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RegisterPlugin(ctx context.Context, in *RegisterPluginRequest, opts ...grpc.CallOption) (*PluginVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginVersion)
	err := c.cc.Invoke(ctx, Runtime_RegisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ActivatePlugin(ctx context.Context, in *ActivatePluginRequest, opts ...grpc.CallOption) (*PluginVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginVersion)
	err := c.cc.Invoke(ctx, Runtime_ActivatePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RollbackPlugin(ctx context.Context, in *RollbackPluginRequest, opts ...grpc.CallOption) (*PluginVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginVersion)
	err := c.cc.Invoke(ctx, Runtime_RollbackPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	// Synchronous inference. With `agent` set, starts that agent and waits for its result.
	Infer(context.Context, *InferenceRequest) (*InferenceResponse, error)
	// Streaming inference: start, token deltas, usage, exactly one terminal event.
	InferStream(*InferenceRequest, grpc.ServerStreamingServer[Event]) error
	ExecuteTool(context.Context, *ToolRequest) (*ToolResult, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentVersion, error)
	StartRun(context.Context, *RunRequest) (*Run, error)
	GetRun(context.Context, *GetRunRequest) (*Run, error)
	// Ordered, durable run events. Resumable: pass the last seen seq as after_seq.
	WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[Event]) error
	// Idempotent.
	CancelRun(context.Context, *CancelRunRequest) (*Run, error)
	// Resolve a run in needs_attention after an ambiguous external write.
	ResolveRun(context.Context, *ResolveRunRequest) (*Run, error)
	// Offline: never calls a model, tool, plugin or network endpoint.
	DryRun(context.Context, *DryRunRequest) (*DryRunReport, error)
	// Contract reserved for M9; the MVP returns UNIMPLEMENTED / HTTP 501.
	DecideApproval(context.Context, *ApprovalDecision) (*Approval, error)
	// Plugins (administrators only). Versions are immutable; activation validates and health-checks
	// the version and affects new runs only (running runs keep the versions they started with).
	RegisterPlugin(context.Context, *RegisterPluginRequest) (*PluginVersion, error)
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	ActivatePlugin(context.Context, *ActivatePluginRequest) (*PluginVersion, error)
	RollbackPlugin(context.Context, *RollbackPluginRequest) (*PluginVersion, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) Infer(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedRuntimeServer) InferStream(*InferenceRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method InferStream not implemented")
}
func (UnimplementedRuntimeServer) ExecuteTool(context.Context, *ToolRequest) (*ToolResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedRuntimeServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedRuntimeServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedRuntimeServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*AgentVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedRuntimeServer) StartRun(context.Context, *RunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRuntimeServer) GetRun(context.Context, *GetRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRuntimeServer) WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchRun not implemented")
}
func (UnimplementedRuntimeServer) CancelRun(context.Context, *CancelRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedRuntimeServer) ResolveRun(context.Context, *ResolveRunRequest) (*Run, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveRun not implemented")
}
func (UnimplementedRuntimeServer) DryRun(context.Context, *DryRunRequest) (*DryRunReport, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRun not implemented")
}
func (UnimplementedRuntimeServer) DecideApproval(context.Context, *ApprovalDecision) (*Approval, error) {
	return nil, status.Error(codes.Unimplemented, "method DecideApproval not implemented")
}
func (UnimplementedRuntimeServer) RegisterPlugin(context.Context, *RegisterPluginRequest) (*PluginVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPlugin not implemented")
}
func (UnimplementedRuntimeServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedRuntimeServer) ActivatePlugin(context.Context, *ActivatePluginRequest) (*PluginVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivatePlugin not implemented")
}
func (UnimplementedRuntimeServer) RollbackPlugin(context.Context, *RollbackPluginRequest) (*PluginVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackPlugin not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Infer(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_InferStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InferenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).InferStream(m, &grpc.GenericServerStream[InferenceRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_InferStreamServer = grpc.ServerStreamingServer[Event]

func _Runtime_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ExecuteTool(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StartRun(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_WatchRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).WatchRun(m, &grpc.GenericServerStream[WatchRunRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_WatchRunServer = grpc.ServerStreamingServer[Event]

func _Runtime_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ResolveRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ResolveRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ResolveRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ResolveRun(ctx, req.(*ResolveRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DryRun(ctx, req.(*DryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DecideApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalDecision)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DecideApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DecideApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DecideApproval(ctx, req.(*ApprovalDecision))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RegisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RegisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RegisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RegisterPlugin(ctx, req.(*RegisterPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ActivatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ActivatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ActivatePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ActivatePlugin(ctx, req.(*ActivatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RollbackPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RollbackPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RollbackPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RollbackPlugin(ctx, req.(*RollbackPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uar.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _Runtime_Infer_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _Runtime_ExecuteTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Runtime_ListTools_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Runtime_ListModels_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _Runtime_RegisterAgent_Handler,
		},
		{
			MethodName: "StartRun",
			Handler:    _Runtime_StartRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _Runtime_GetRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _Runtime_CancelRun_Handler,
		},
		{
			MethodName: "ResolveRun",
			Handler:    _Runtime_ResolveRun_Handler,
		},
		{
			MethodName: "DryRun",
			Handler:    _Runtime_DryRun_Handler,
		},
		{
			MethodName: "DecideApproval",
			Handler:    _Runtime_DecideApproval_Handler,
		},
		{
			MethodName: "RegisterPlugin",
			Handler:    _Runtime_RegisterPlugin_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _Runtime_ListPlugins_Handler,
		},
		{
			MethodName: "ActivatePlugin",
			Handler:    _Runtime_ActivatePlugin_Handler,
		},
		{
			MethodName: "RollbackPlugin",
			Handler:    _Runtime_RollbackPlugin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InferStream",
			Handler:       _Runtime_InferStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRun",
			Handler:       _Runtime_WatchRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "uarpb/v1/runtime.proto",
}
