"""Create a private local configuration with API keys.

    python scripts/bootstrap_local.py            # .local/uar.yaml + .local/credentials.env
    python scripts/bootstrap_local.py --k8s      # also .local/uar-k8s.yaml for the Helm chart
    python scripts/bootstrap_local.py --force    # regenerate keys

Keys live only in .local/credentials.env (git-ignored); configs store their SHA-256.
Existing keys are reused unless --force is given.
"""
from __future__ import annotations

import argparse
import hashlib
import secrets
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
LOCAL = ROOT / ".local"
ROLES = ("DEV", "ADMIN", "OPS")


def new_key() -> str:
    return f"uar_{secrets.token_hex(4)}_{secrets.token_urlsafe(24)}"


def load_creds(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return dict(line.split("=", 1) for line in path.read_text(encoding="utf-8").splitlines() if "=" in line)


def render(template: str, creds: dict[str, str]) -> str:
    for role in ROLES:
        key = creds[f"UAR_{role}_KEY"]
        template = template.replace(f"__{role}_ID__", key.split("_")[1]) \
                           .replace(f"__{role}_SHA__", hashlib.sha256(key.encode()).hexdigest())
    return template


def k8s_variant(text: str, port: int = 8765, ns: str = "uar-plugins") -> str:
    cfg = yaml.safe_load(text)
    cfg["server"]["host"] = "0.0.0.0"
    cfg.setdefault("egress", {})["allow_private"] = ["127.0.0.0/8", "10.0.0.0/8"]
    overrides = {s["id"]: s.get("tools", {}) for s in cfg.get("mcp_servers", [])}
    cfg["mcp_servers"] = [
        {"id": sid, "transport": "http", "url": f"http://uar-mcp-{sid}.{ns}.svc.cluster.local:{port}/mcp",
         "tools": overrides.get(sid, {}), "timeout_s": 30}
        for sid in ("fs", "db")]
    cfg["agents_dir"] = "/app/examples/agents"
    header = ("# Generated by scripts/bootstrap_local.py --k8s for the Helm chart (deploy/helm/uar).\n"
              "# MCP servers run as Deployments in the uar-plugins namespace (Streamable HTTP).\n")
    return header + yaml.safe_dump(cfg, sort_keys=False)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="generate new keys")
    ap.add_argument("--k8s", action="store_true", help="also write .local/uar-k8s.yaml")
    ap.add_argument("--config", default=str(ROOT / "config" / "uar.example.yaml"))
    a = ap.parse_args()
    LOCAL.mkdir(exist_ok=True)
    creds_path = LOCAL / "credentials.env"
    creds = {} if a.force else load_creds(creds_path)
    if not all(f"UAR_{r}_KEY" in creds for r in ROLES):
        creds = {f"UAR_{r}_KEY": new_key() for r in ROLES} | {"UAR_JWT_SECRET": secrets.token_urlsafe(32)}
        creds_path.write_text("".join(f"{k}={v}\n" for k, v in creds.items()), encoding="utf-8")
        print(f"wrote new keys to {creds_path.relative_to(ROOT)} (keep it private)")
    text = render(Path(a.config).read_text(encoding="utf-8"), creds)
    (LOCAL / "uar.yaml").write_text(text, encoding="utf-8")
    print("wrote .local/uar.yaml")
    if a.k8s:
        (LOCAL / "uar-k8s.yaml").write_text(k8s_variant(text), encoding="utf-8")
        print("wrote .local/uar-k8s.yaml")


if __name__ == "__main__":
    main()
