// Universal AI Runtime — plugin protocol, version 1.
// Plugins (model, tool, agent) run out of process and implement this service.
// Contract defined in M0; the runtime-side plugin supervisor is delivered in M7.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: uarpb/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginDescriptor struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version      string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind         string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // model | tool | agent
	Api          string                 `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`   // "uar.plugin.v1"
	Capabilities []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ConfigSchema *structpb.Struct       `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	InputSchema  *structpb.Struct       `protobuf:"bytes,7,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema *structpb.Struct       `protobuf:"bytes,8,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// Tool plugins: the tools they expose.
	Tools []*ToolDescriptor `protobuf:"bytes,9,rep,name=tools,proto3" json:"tools,omitempty"`
	// Model plugins: the model ids they serve.
	Models        []string `protobuf:"bytes,10,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginDescriptor) Reset() {
	*x = PluginDescriptor{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDescriptor) ProtoMessage() {}

func (x *PluginDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDescriptor.ProtoReflect.Descriptor instead.
func (*PluginDescriptor) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PluginDescriptor) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *PluginDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginDescriptor) GetConfigSchema() *structpb.Struct {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *PluginDescriptor) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *PluginDescriptor) GetOutputSchema() *structpb.Struct {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *PluginDescriptor) GetTools() []*ToolDescriptor {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *PluginDescriptor) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

type ToolDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	SideEffect    string                 `protobuf:"bytes,4,opt,name=side_effect,json=sideEffect,proto3" json:"side_effect,omitempty"` // read | write | external
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDescriptor) Reset() {
	*x = ToolDescriptor{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptor) ProtoMessage() {}

func (x *ToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptor.ProtoReflect.Descriptor instead.
func (*ToolDescriptor) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDescriptor) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *ToolDescriptor) GetSideEffect() string {
	if x != nil {
		return x.SideEffect
	}
	return ""
}

type PluginInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *structpb.Struct       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`                                                                             // validated against config_schema
	Secrets       map[string]string      `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // resolved secret references only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInitRequest) Reset() {
	*x = PluginInitRequest{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInitRequest) ProtoMessage() {}

func (x *PluginInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInitRequest.ProtoReflect.Descriptor instead.
func (*PluginInitRequest) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginInitRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PluginInitRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type PluginInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInitResponse) Reset() {
	*x = PluginInitResponse{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInitResponse) ProtoMessage() {}

func (x *PluginInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInitResponse.ProtoReflect.Descriptor instead.
func (*PluginInitResponse) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PluginInitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PluginInitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecutionContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tenant          string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeadlineUnixMs  int64                  `protobuf:"varint,4,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CapabilityToken string                 `protobuf:"bytes,6,opt,name=capability_token,json=capabilityToken,proto3" json:"capability_token,omitempty"`
	Traceparent     string                 `protobuf:"bytes,7,opt,name=traceparent,proto3" json:"traceparent,omitempty"` // W3C trace context
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ExecutionContext) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionContext) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *ExecutionContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecutionContext) GetCapabilityToken() string {
	if x != nil {
		return x.CapabilityToken
	}
	return ""
}

func (x *ExecutionContext) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

type ModelCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*structpb.Struct     `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"` // uar.v1.ChatMessage JSON
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Tools         []*structpb.Struct     `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCall) Reset() {
	*x = ModelCall{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCall) ProtoMessage() {}

func (x *ModelCall) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCall.ProtoReflect.Descriptor instead.
func (*ModelCall) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ModelCall) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelCall) GetMessages() []*structpb.Struct {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ModelCall) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ModelCall) GetTools() []*structpb.Struct {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCall) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCall) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type AgentCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCall) Reset() {
	*x = AgentCall{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCall) ProtoMessage() {}

func (x *AgentCall) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCall.ProtoReflect.Descriptor instead.
func (*AgentCall) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *AgentCall) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *AgentCall) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type PluginExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ctx   *ExecutionContext      `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	// Types that are valid to be assigned to Call:
	//
	//	*PluginExecuteRequest_Model
	//	*PluginExecuteRequest_Tool
	//	*PluginExecuteRequest_Agent
	Call          isPluginExecuteRequest_Call `protobuf_oneof:"call"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginExecuteRequest) Reset() {
	*x = PluginExecuteRequest{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginExecuteRequest) ProtoMessage() {}

func (x *PluginExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginExecuteRequest.ProtoReflect.Descriptor instead.
func (*PluginExecuteRequest) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PluginExecuteRequest) GetCtx() *ExecutionContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *PluginExecuteRequest) GetCall() isPluginExecuteRequest_Call {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *PluginExecuteRequest) GetModel() *ModelCall {
	if x != nil {
		if x, ok := x.Call.(*PluginExecuteRequest_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *PluginExecuteRequest) GetTool() *ToolCall {
	if x != nil {
		if x, ok := x.Call.(*PluginExecuteRequest_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *PluginExecuteRequest) GetAgent() *AgentCall {
	if x != nil {
		if x, ok := x.Call.(*PluginExecuteRequest_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

type isPluginExecuteRequest_Call interface {
	isPluginExecuteRequest_Call()
}

type PluginExecuteRequest_Model struct {
	Model *ModelCall `protobuf:"bytes,10,opt,name=model,proto3,oneof"`
}

type PluginExecuteRequest_Tool struct {
	Tool *ToolCall `protobuf:"bytes,11,opt,name=tool,proto3,oneof"`
}

type PluginExecuteRequest_Agent struct {
	Agent *AgentCall `protobuf:"bytes,12,opt,name=agent,proto3,oneof"`
}

func (*PluginExecuteRequest_Model) isPluginExecuteRequest_Call() {}

func (*PluginExecuteRequest_Tool) isPluginExecuteRequest_Call() {}

func (*PluginExecuteRequest_Agent) isPluginExecuteRequest_Call() {}

type PluginExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsError       bool                   `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	InputTokens   int32                  `protobuf:"varint,6,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,7,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	FinishReason  string                 `protobuf:"bytes,8,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginExecuteResponse) Reset() {
	*x = PluginExecuteResponse{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginExecuteResponse) ProtoMessage() {}

func (x *PluginExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginExecuteResponse.ProtoReflect.Descriptor instead.
func (*PluginExecuteResponse) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PluginExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *PluginExecuteResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PluginExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PluginExecuteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PluginExecuteResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *PluginExecuteResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *PluginExecuteResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *PluginExecuteResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type PluginEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PluginEvent_Token
	//	*PluginEvent_Final
	Body          isPluginEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PluginEvent) GetBody() isPluginEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PluginEvent) GetToken() string {
	if x != nil {
		if x, ok := x.Body.(*PluginEvent_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *PluginEvent) GetFinal() *PluginExecuteResponse {
	if x != nil {
		if x, ok := x.Body.(*PluginEvent_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isPluginEvent_Body interface {
	isPluginEvent_Body()
}

type PluginEvent_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type PluginEvent_Final struct {
	Final *PluginExecuteResponse `protobuf:"bytes,2,opt,name=final,proto3,oneof"`
}

func (*PluginEvent_Token) isPluginEvent_Body() {}

func (*PluginEvent_Final) isPluginEvent_Body() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serving       bool                   `protobuf:"varint,1,opt,name=serving,proto3" json:"serving,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponse) GetServing() bool {
	if x != nil {
		return x.Serving
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceMs       int32                  `protobuf:"varint,1,opt,name=grace_ms,json=graceMs,proto3" json:"grace_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ShutdownRequest) GetGraceMs() int32 {
	if x != nil {
		return x.GraceMs
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uarpb_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_uarpb_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

var File_uarpb_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_uarpb_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cuarpb/plugin/v1/plugin.proto\x12\ruar.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x11\n" +
	"\x0fDescribeRequest\"\x8b\x03\n" +
	"\x10PluginDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x10\n" +
	"\x03api\x18\x04 \x01(\tR\x03api\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12<\n" +
	"\rconfig_schema\x18\x06 \x01(\v2\x17.google.protobuf.StructR\fconfigSchema\x12:\n" +
	"\finput_schema\x18\a \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12<\n" +
	"\routput_schema\x18\b \x01(\v2\x17.google.protobuf.StructR\foutputSchema\x123\n" +
	"\x05tools\x18\t \x03(\v2\x1d.uar.plugin.v1.ToolDescriptorR\x05tools\x12\x16\n" +
	"\x06models\x18\n" +
	" \x03(\tR\x06models\"\xa3\x01\n" +
	"\x0eToolDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12\x1f\n" +
	"\vside_effect\x18\x04 \x01(\tR\n" +
	"sideEffect\"\xc9\x01\n" +
	"\x11PluginInitRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\x12G\n" +
	"\asecrets\x18\x02 \x03(\v2-.uar.plugin.v1.PluginInitRequest.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x12PluginInitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x02\n" +
	"\x10ExecutionContext\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12(\n" +
	"\x10deadline_unix_ms\x18\x04 \x01(\x03R\x0edeadlineUnixMs\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10capability_token\x18\x06 \x01(\tR\x0fcapabilityToken\x12 \n" +
	"\vtraceparent\x18\a \x01(\tR\vtraceparent\"\xb6\x01\n" +
	"\tModelCall\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.google.protobuf.StructR\bmessages\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\x12-\n" +
	"\x05tools\x18\x04 \x03(\v2\x17.google.protobuf.StructR\x05tools\"K\n" +
	"\bToolCall\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\"P\n" +
	"\tAgentCall\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\"\xe4\x01\n" +
	"\x14PluginExecuteRequest\x121\n" +
	"\x03ctx\x18\x01 \x01(\v2\x1f.uar.plugin.v1.ExecutionContextR\x03ctx\x120\n" +
	"\x05model\x18\n" +
	" \x01(\v2\x18.uar.plugin.v1.ModelCallH\x00R\x05model\x12-\n" +
	"\x04tool\x18\v \x01(\v2\x17.uar.plugin.v1.ToolCallH\x00R\x04tool\x120\n" +
	"\x05agent\x18\f \x01(\v2\x18.uar.plugin.v1.AgentCallH\x00R\x05agentB\x06\n" +
	"\x04call\"\xa8\x02\n" +
	"\x15PluginExecuteResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12/\n" +
	"\x06output\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06output\x12!\n" +
	"\finput_tokens\x18\x06 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\a \x01(\x05R\foutputTokens\x12#\n" +
	"\rfinish_reason\x18\b \x01(\tR\ffinishReason\"k\n" +
	"\vPluginEvent\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12<\n" +
	"\x05final\x18\x02 \x01(\v2$.uar.plugin.v1.PluginExecuteResponseH\x00R\x05finalB\x06\n" +
	"\x04body\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aserving\x18\x01 \x01(\bR\aserving\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x0fShutdownRequest\x12\x19\n" +
	"\bgrace_ms\x18\x01 \x01(\x05R\agraceMs\"\x12\n" +
	"\x10ShutdownResponse2\xe0\x03\n" +
	"\x06Plugin\x12K\n" +
	"\bDescribe\x12\x1e.uar.plugin.v1.DescribeRequest\x1a\x1f.uar.plugin.v1.PluginDescriptor\x12K\n" +
	"\x04Init\x12 .uar.plugin.v1.PluginInitRequest\x1a!.uar.plugin.v1.PluginInitResponse\x12T\n" +
	"\aExecute\x12#.uar.plugin.v1.PluginExecuteRequest\x1a$.uar.plugin.v1.PluginExecuteResponse\x12R\n" +
	"\rExecuteStream\x12#.uar.plugin.v1.PluginExecuteRequest\x1a\x1a.uar.plugin.v1.PluginEvent0\x01\x12E\n" +
	"\x06Health\x12\x1c.uar.plugin.v1.HealthRequest\x1a\x1d.uar.plugin.v1.HealthResponse\x12K\n" +
	"\bShutdown\x12\x1e.uar.plugin.v1.ShutdownRequest\x1a\x1f.uar.plugin.v1.ShutdownResponseBu\n" +
	"\x11dev.uar.plugin.v1P\x01ZNgithub.com/washim1982/universal-ai-runtime-v1/plugin-sdks/go/pluginv1;pluginv1\xaa\x02\rUar.Plugin.V1b\x06proto3"

var (
	file_uarpb_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_uarpb_plugin_v1_plugin_proto_rawDescData []byte
)

func file_uarpb_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_uarpb_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_uarpb_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_uarpb_plugin_v1_plugin_proto_rawDesc), len(file_uarpb_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_uarpb_plugin_v1_plugin_proto_rawDescData
}

var file_uarpb_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_uarpb_plugin_v1_plugin_proto_goTypes = []any{
	(*DescribeRequest)(nil),       // 0: uar.plugin.v1.DescribeRequest
	(*PluginDescriptor)(nil),      // 1: uar.plugin.v1.PluginDescriptor
	(*ToolDescriptor)(nil),        // 2: uar.plugin.v1.ToolDescriptor
	(*PluginInitRequest)(nil),     // 3: uar.plugin.v1.PluginInitRequest
	(*PluginInitResponse)(nil),    // 4: uar.plugin.v1.PluginInitResponse
	(*ExecutionContext)(nil),      // 5: uar.plugin.v1.ExecutionContext
	(*ModelCall)(nil),             // 6: uar.plugin.v1.ModelCall
	(*ToolCall)(nil),              // 7: uar.plugin.v1.ToolCall
	(*AgentCall)(nil),             // 8: uar.plugin.v1.AgentCall
	(*PluginExecuteRequest)(nil),  // 9: uar.plugin.v1.PluginExecuteRequest
	(*PluginExecuteResponse)(nil), // 10: uar.plugin.v1.PluginExecuteResponse
	(*PluginEvent)(nil),           // 11: uar.plugin.v1.PluginEvent
	(*HealthRequest)(nil),         // 12: uar.plugin.v1.HealthRequest
	(*HealthResponse)(nil),        // 13: uar.plugin.v1.HealthResponse
	(*ShutdownRequest)(nil),       // 14: uar.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 15: uar.plugin.v1.ShutdownResponse
	nil,                           // 16: uar.plugin.v1.PluginInitRequest.SecretsEntry
	(*structpb.Struct)(nil),       // 17: google.protobuf.Struct
}
var file_uarpb_plugin_v1_plugin_proto_depIdxs = []int32{
	17, // 0: uar.plugin.v1.PluginDescriptor.config_schema:type_name -> google.protobuf.Struct
	17, // 1: uar.plugin.v1.PluginDescriptor.input_schema:type_name -> google.protobuf.Struct
	17, // 2: uar.plugin.v1.PluginDescriptor.output_schema:type_name -> google.protobuf.Struct
	2,  // 3: uar.plugin.v1.PluginDescriptor.tools:type_name -> uar.plugin.v1.ToolDescriptor
	17, // 4: uar.plugin.v1.ToolDescriptor.input_schema:type_name -> google.protobuf.Struct
	17, // 5: uar.plugin.v1.PluginInitRequest.config:type_name -> google.protobuf.Struct
	16, // 6: uar.plugin.v1.PluginInitRequest.secrets:type_name -> uar.plugin.v1.PluginInitRequest.SecretsEntry
	17, // 7: uar.plugin.v1.ModelCall.messages:type_name -> google.protobuf.Struct
	17, // 8: uar.plugin.v1.ModelCall.params:type_name -> google.protobuf.Struct
	17, // 9: uar.plugin.v1.ModelCall.tools:type_name -> google.protobuf.Struct
	17, // 10: uar.plugin.v1.ToolCall.args:type_name -> google.protobuf.Struct
	17, // 11: uar.plugin.v1.AgentCall.input:type_name -> google.protobuf.Struct
	5,  // 12: uar.plugin.v1.PluginExecuteRequest.ctx:type_name -> uar.plugin.v1.ExecutionContext
	6,  // 13: uar.plugin.v1.PluginExecuteRequest.model:type_name -> uar.plugin.v1.ModelCall
	7,  // 14: uar.plugin.v1.PluginExecuteRequest.tool:type_name -> uar.plugin.v1.ToolCall
	8,  // 15: uar.plugin.v1.PluginExecuteRequest.agent:type_name -> uar.plugin.v1.AgentCall
	17, // 16: uar.plugin.v1.PluginExecuteResponse.output:type_name -> google.protobuf.Struct
	10, // 17: uar.plugin.v1.PluginEvent.final:type_name -> uar.plugin.v1.PluginExecuteResponse
	0,  // 18: uar.plugin.v1.Plugin.Describe:input_type -> uar.plugin.v1.DescribeRequest
	3,  // 19: uar.plugin.v1.Plugin.Init:input_type -> uar.plugin.v1.PluginInitRequest
	9,  // 20: uar.plugin.v1.Plugin.Execute:input_type -> uar.plugin.v1.PluginExecuteRequest
	9,  // 21: uar.plugin.v1.Plugin.ExecuteStream:input_type -> uar.plugin.v1.PluginExecuteRequest
	12, // 22: uar.plugin.v1.Plugin.Health:input_type -> uar.plugin.v1.HealthRequest
	14, // 23: uar.plugin.v1.Plugin.Shutdown:input_type -> uar.plugin.v1.ShutdownRequest
	1,  // 24: uar.plugin.v1.Plugin.Describe:output_type -> uar.plugin.v1.PluginDescriptor
	4,  // 25: uar.plugin.v1.Plugin.Init:output_type -> uar.plugin.v1.PluginInitResponse
	10, // 26: uar.plugin.v1.Plugin.Execute:output_type -> uar.plugin.v1.PluginExecuteResponse
	11, // 27: uar.plugin.v1.Plugin.ExecuteStream:output_type -> uar.plugin.v1.PluginEvent
	13, // 28: uar.plugin.v1.Plugin.Health:output_type -> uar.plugin.v1.HealthResponse
	15, // 29: uar.plugin.v1.Plugin.Shutdown:output_type -> uar.plugin.v1.ShutdownResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_uarpb_plugin_v1_plugin_proto_init() }
func file_uarpb_plugin_v1_plugin_proto_init() {
	if File_uarpb_plugin_v1_plugin_proto != nil {
		return
	}
	file_uarpb_plugin_v1_plugin_proto_msgTypes[9].OneofWrappers = []any{
		(*PluginExecuteRequest_Model)(nil),
		(*PluginExecuteRequest_Tool)(nil),
		(*PluginExecuteRequest_Agent)(nil),
	}
	file_uarpb_plugin_v1_plugin_proto_msgTypes[11].OneofWrappers = []any{
		(*PluginEvent_Token)(nil),
		(*PluginEvent_Final)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_uarpb_plugin_v1_plugin_proto_rawDesc), len(file_uarpb_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uarpb_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_uarpb_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_uarpb_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_uarpb_plugin_v1_plugin_proto = out.File
	file_uarpb_plugin_v1_plugin_proto_goTypes = nil
	file_uarpb_plugin_v1_plugin_proto_depIdxs = nil
}
